<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 /Users/youwenw/Projects/JS/threlte-demo/static/models/scene.gltf --root /models/ --types --printwidth 120 --precision 2
Author: cs09736 (https://sketchfab.com/cs09736)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-fa-18-hornet-9b48c88e91ba40fc8f518b616f44f714
Title: Low Poly F/A-18 Hornet
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import {
    T,
    type Props,
    type Events,
    type Slots,
    forwardEventHandlers,
  } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      Object_4: THREE.Mesh
      Object_5: THREE.Mesh
      Object_6: THREE.Mesh
      Object_7: THREE.Mesh
      Object_8: THREE.Mesh
      Object_9: THREE.Mesh
      Object_10: THREE.Mesh
    }
    materials: {
      clay: THREE.MeshStandardMaterial
      engine_inside: THREE.MeshStandardMaterial
      body_paint: THREE.MeshStandardMaterial
      glass: THREE.MeshStandardMaterial
      after_burner: THREE.MeshStandardMaterial
      strut: THREE.MeshStandardMaterial
      tyre: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/src/assets/models/scene.gltf')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group rotation={[-Math.PI / 2, 0, 0]} scale={2}>
      <T.Group rotation={[Math.PI / 2, 0, 0]}>
        <T.Mesh
          geometry={gltf.nodes.Object_4.geometry}
          material={gltf.materials.clay}
        />
        <T.Mesh
          geometry={gltf.nodes.Object_5.geometry}
          material={gltf.materials.engine_inside}
        />
        <T.Mesh
          geometry={gltf.nodes.Object_6.geometry}
          material={gltf.materials.body_paint}
        />
        <T.Mesh
          geometry={gltf.nodes.Object_7.geometry}
          material={gltf.materials.glass}
        />
        <T.Mesh
          geometry={gltf.nodes.Object_8.geometry}
          material={gltf.materials.after_burner}
        />
        <T.Mesh
          geometry={gltf.nodes.Object_9.geometry}
          material={gltf.materials.strut}
        />
        <T.Mesh
          geometry={gltf.nodes.Object_10.geometry}
          material={gltf.materials.tyre}
        />
      </T.Group>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
